import os

APP_PORT = os.getenv('APP_PORT', 8088)

POSTGRESQL_DB_HOST = os.getenv('PG_DB_HOST')
POSTGRESQL_DB_NAME = os.getenv('PG_DB_NAME')
POSTGRESQL_DB_USER = os.getenv('PG_DB_USER')
POSTGRESQL_DB_PORT = '5432'
POSTGRESQL_DB_PASSWORD = os.getenv('PG_DB_PASS')
